image: cypress/base:10.16.0
  stages:
    - build

  build:
    stage: build
    image: cypress/base:10
    script:
      - echo "Start building App"
      - yarn install
      - yarn audit:ci
      - yarn lint
      - yarn test
      - yarn build
      - yarn cypress install > /dev/null && yarn cy:ci
      - echo "Build successfully!"
    artifacts:
      expire_in: 1 hour
      paths:
        - build
        - node_modules/
