image: cypress/base:10.16.0
  stages:
    - test

  cache:
    paths:
      - node_modules/

  install_dependencies:
    stage: test
    script:
      - yarn install
    artifacts:
      paths:
        - node_modules/

  audit_vulnerabilities:
    stage: test
    script: yarn audit:ci

  static_code_analyze:
    stage: test
    script: yarn lint
  
  unit_test:
    stage: test
    script: yarn test

  run_compilation:
    stage: test
    script: yarn build
  
  run_integration_tests:
    script: yarn cypress install > /dev/null && yarn cy:ci