image: cypress/base:10.16.0

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - yarn install
          - yarn audit:ci
          - yarn lint
          - yarn test
          - yarn build
          - yarn cypress install
          - yarn cy:ci
